version: '3.8'

services:
  app:
    image: akunmkepl/Web-Mahasiswa:latest
    container_name: Container_Mahasiswa
    ports:
      - "8000:9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: akademik
      DB_USERNAME: root
      DB_PASSWORD: 
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
