services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Nama Dockerfile Anda
    image: villysatria/web-mahasiswa:latest  # Ganti dengan nama image Laravel Anda
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Password untuk root MySQL
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network


networks:
  laravel-net:
    driver: bridge

volumes:
  mysql_data:
    driver: local
